### ISSUE TITLE
Eliminate non-inclusive language

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/mssql#155]
Hello, we have a project to eliminate non-inclusive language from Linux-system-roles.

Running a utility `woke` (now it's supported in tox. please install the latest tox-lsr and run tox -e woke), two non-inclusive words are reported - `sanity` and `master`.

The word `sanity` is easily eliminated, but `master` is not since it's tightly coupled with the SQL context, e.g., as `master key`.

There are two ways to skip the check - adding `wokeignore:rule=master` to each `master` appearing in the source code, or skipping them as `warning` by applying https://github.com/get-woke/woke/pull/252. Which way should we go or could there be some other ideas to workaround `master`?

**Comment by spetrosi** [comment]
There are too many uses of `master` in the code. Running woke with `--count-only-error-for-failure` results in a success, so it's only the word master that matters. And the role cannot fix `master` in the SQL Server context. The role can only fix the use of `master` in unrelated context, e.g. rename the GitHub branch `master` > `main`.

**Comment by nhosoi** [comment]
Thank you for your comments, @spetrosi! Your proposal makes sense.

First, may I ask you to rename the `master` branch to the `main` branch as described in https://issues.redhat.com/browse/RHELPLAN-134435 by @richm.

Then, we can reduce the number of the word `master` before applying the `--count-only-error-for-failure` change. Thanks!

**Comment by nhosoi** [comment]
Thank you for merging https://github.com/linux-system-roles/mssql/pull/158, @spetrosi.
Closing this issue.
