### ISSUE TITLE
Conscious Language: Please rename master branch to main branch

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/mssql#163]
As part of the conscious language project, the master branch is to be renamed to the main branch.

Here are the instructions.

1. Rename the master branch to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
2. Check this to ensure the default branch has been changed to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch - this should keep the github history, as well as updating the default branch configuration and updating any existing PRs

If you use the gh cli (highly recommended) you can use this to check which repos need to be updated:
```
gh repo list linux-system-roles -L 100 --json name,defaultBranchRef --source | \
  jq --raw-output '.[] | select(.defaultBranchRef.name == "master") | .name'
```
Thanks.

**Comment by nhosoi** [comment]
@spetrosi, The selinux role shares the same concern you shared regarding the transition. @richm used `git symbolic-ref` to keep the master branch as a symbolic ref (see also https://github.com/linux-system-roles/selinux/issues/137). If it fits in the mssql's needs, could you please take the same steps?

Once it's done, we can lift WIP in https://github.com/linux-system-roles/mssql/pull/158.
> Note: the changes in .collection/README.md and .collection/galaxy.yml expect the master branch to be renamed to main branch. I.e., until it happens, we want to keep this pr as a draft.

**Comment by spetrosi** [comment]
Hi @nhosoi, I've renamed master to main, you can proceed with this.
