### ISSUE TITLE
README should explicitly state which parameters are required and which are optional

### ISSUE THREAD

**Issue by richm** [linux-system-roles/mssql#26]
It isn't clear from the README which parameters are required and which are optional.  The description for each parameter should specify if this parameter is required or optional.

We should provide in the README an example playbook which sets the minimal required parameters, and perhaps use the current example as an example of how to also set the optional parameters.  Then users could copy/paste the minimal and add their own as needed.
@spetrosi

**Comment by spetrosi** [comment]
I agree, the example playbook grew and became unclear. I've split it into several playbooks serving different user stories, please review.
