### ISSUE TITLE
Clarify how TLS files are created and used

### ISSUE THREAD

**Issue by richm** [linux-system-roles/mssql#27]
It isn't clear from the documentation that the role *does not* create the TLS cert/key files if not specified.  We should state something like "You are responsible for creating and securing the TLS cert and key file.  It is assumed you have a CA which can issue these files.  If not, you can use the `openssl` command to create these files."

**Comment by spetrosi** [comment]
Thanks for the review, Rich. I've opened a PR to clarify this, please review.
