### ISSUE TITLE
Using role to setup SQL Server availability group clustering not working if FQDN hostnames are used in inventory

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/mssql#85]
If FQDN hostnames are used in the inventory to setup a SQL Server availability group, the resulting cluster does not work properly.  The SQL error log shows seeding errors on one of the nodes and "pcs status" never stabilizes.  

When using short host names in the inventory, everything appears to work correctly.

**Comment by spetrosi** [comment]
Hi @briansmith0,

thank you for troubleshooting this. I will fix this.

To provide some context, mssql uses FQDN when creating AG replicas - endpoint URL is specified as FQDN.
```
  CREATE AVAILABILITY GROUP ag1
    WITH (DB_FAILOVER = ON, CLUSTER_TYPE = EXTERNAL)
    FOR REPLICA ON
      N'primary' WITH (
        ENDPOINT_URL = N'tcp://primary.example.com:5022',
        AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
        FAILOVER_MODE = EXTERNAL,
        SEEDING_MODE = AUTOMATIC,
        SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
      ),
      N'secondary' WITH (
        ENDPOINT_URL = N'tcp://secondary.example.com:5022',
        AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
        FAILOVER_MODE = EXTERNAL,
        SEEDING_MODE = AUTOMATIC,
        SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
      );
```
I was using the following MS documentation, it says to use FQDN hence I used it in role: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-configure-ha?view=sql-server-ver15#readScale
